package server

// The v0.27 PWA install shell: the web app manifest, the service worker,
// and the offline fallback page, embedded beside the shell templates and
// served at the site root so the worker's scope covers every page. The
// boundary law lives in the worker's source and docs/pwa-shell.md: the
// worker answers only its explicit asset allowlist and document navigations,
// never /api/ or the room SSE event streams. The icons it references live
// in the static tree (web/static/icons, regenerated by `make icons`).

import (
	"embed"
	"net/http"
)

//go:embed web/pwa
var pwaFS embed.FS

// PWA route paths and header values. The worker script and the manifest
// must revalidate on every fetch: the browser checks the worker script for
// updates there, and both are tiny files that change with deploys.
const (
	manifestRoute = "/manifest.webmanifest"
	swRoute       = "/sw.js"
	offlineRoute  = "/offline.html"

	manifestContentType = "application/manifest+json"
	pwaScriptType       = "text/javascript; charset=utf-8"
	pwaCacheControl     = "no-cache"
)

// mountPWA wires the three root-level PWA routes onto the shell mux, so the
// worker sits at /sw.js with the whole site in its scope.
func mountPWA(mux *http.ServeMux) {
	mux.HandleFunc("GET "+manifestRoute, servePWAFile("manifest.webmanifest", manifestContentType))
	mux.HandleFunc("GET "+swRoute, servePWAFile("sw.js", pwaScriptType))
	mux.HandleFunc("GET "+offlineRoute, servePWAFile("offline.html", "text/html; charset=utf-8"))
}

// servePWAFile serves one embedded PWA file bytes-for-bytes under its exact
// content type. A missing embedded file is a packaging bug; it surfaces as
// the mux's own 404.
func servePWAFile(name, contentType string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		data, err := pwaFS.ReadFile("web/pwa/" + name)
		if err != nil {
			http.NotFound(w, r)
			return
		}
		w.Header().Set("Content-Type", contentType)
		w.Header().Set("Cache-Control", pwaCacheControl)
		_, _ = w.Write(data)
	}
}
